dist: bionic
language: node_js

node_js:
  - 13.5.0

env:
  - RDB_DB=travis_ci_test RDB_USER=postgres RDB_PASS=

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - npm test
  - npm run verify
