name: CI

on: [push, pull_request]

env:
  RDB_DB:   postgres
  RDB_USER: postgres
  RDB_PASS: postgres
  DEBUG:    true
  DB_HOST:  localhost
  DB_PORT:  5432  # defined below in the services.postgres.ports (the first one)
  LANG:     en_US.UTF-8
  LANGUAGE: en_US.UTF-8
  LC_ALL:   en_US.UTF-8

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ env.RDB_PASS }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Checkout ReBench
        uses: actions/checkout@v3
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: Cache R packages
        uses: actions/cache@v3
        env:
          cache-name: r-libs-420
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('src/stats/install.R') }}-2
          # restore-keys: |
          #   ${{ runner.os }}-${{ env.cache-name }}-
          #   ${{ runner.os }}-

      - name: Cache node modules
        uses: actions/cache@v3
        env:
         cache-name: node-modules
        with:
         # npm cache files are stored in `~/.npm` on Linux/macOS
         path: ~/.npm
         key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package.json', 'package-lock.json') }}
         restore-keys: |
           ${{ runner.os }}-${{ env.cache-name }}-
           ${{ runner.os }}-

      - name: Install R libs
        run: |
          Rscript src/stats/install.R

      - name: NPM CI
        run: |
          npm ci

      - name: Run Tests
        run: |
          npm test
      
      - name: Upload image difference, if there are any
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Image Differences of charts.test.ts
          path: diff-*.png
          if-no-files-found: ignore

      - name: Lint and Formatting
        run: |
          npm run verify
