name: Build Container

on:
  push:
    branches:
      - master
      - docker**
      - compose**

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ReBench
        uses: actions/checkout@v4

      - name: Build and Test Docker Image and Composition
        run: |
          docker compose -f ./docker-compose.yml up --detach
          curl --retry 5 --retry-delay 5 --retry-all-errors http://localhost:33333/status
          docker compose -f ./docker-compose.yml down
