name: CI

on: [push, pull_request]

env:
  RDB_DB:   rebenchdb
  RDB_USER: docker
  RDB_PASS: docker
  DEBUG:    true
  LANG:     en_US.UTF-8
  LANGUAGE: en_US.UTF-8
  LC_ALL:   en_US.UTF-8

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        uses: docker/build-push-action@v3
        with:
          push: false
    
    


     